
#if !defined _CONFIG_H
#define _CONFIG_H

#define CMAKE_INSTALL_PREFIX "/usr/local"
#define CPACK_PACKAGE_VERSION_MAJOR 0
#define CPACK_PACKAGE_VERSION_MINOR 5
#define CPACK_PACKAGE_VERSION_PATCH 1

#endif
